[package]
name = "grezi_skia"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
memmap = "*"
skulpin = { version = "*", features = [
  "skia-textlayout",
  "winit-latest",
  "winit-app",
] }
easing = { git = "https://github.com/StratusFearMe21/easing" }
structopt = "*"
ariadne = "*"
grezi = { path = "../lib_grezi" }
