[package]
name = "grzfmt"
version = "2.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grezi = { path = "../lib_grezi" }
memmap = "0.7.0"
clap = "3.1.3"
