[package]
name = "grzfmt"
version = "1.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grezi = { path = "../lib_grezi" }
memmap = "*"
clap = "*"
