[package]
name = "grezi"
version = "1.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "grezi"


[dependencies]
chumsky = "0.8.0"
glam = "0.20.2"
ahash = "0.7.6"
cassowary = "0.3.0"
rayon = "1.5.1"
